# Generated by Django 2.2.7 on 2020-02-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='headgroup_thickness',
            field=models.FloatField(blank=True, default=8, null=True, verbose_name='headgroup thickness'),
        ),
    ]
