# Generated by Django 2.2.7 on 2020-02-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20200223_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='average_vesicle_radius',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='average vesicle radius'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='headgroup_thickness',
            field=models.FloatField(default=8, verbose_name='headgroup thickness'),
        ),
    ]
