# Generated by Django 2.2.7 on 2019-12-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20191218_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='background',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='background_lock',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='background_lowerbound',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='background_upperbound',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='scale_lock',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='scale_lowerbound',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='scale_upperbound',
        ),
        migrations.AddField(
            model_name='data_set',
            name='background',
            field=models.FloatField(default=0, verbose_name='background'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='background_lock',
            field=models.BooleanField(default=True, verbose_name='sig lock'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='background_lowerbound',
            field=models.FloatField(default=0, verbose_name='sig lower bound'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='background_upperbound',
            field=models.FloatField(default=0, verbose_name='sig upper bound'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='scale',
            field=models.FloatField(default=1, verbose_name='scale'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='scale_lock',
            field=models.BooleanField(default=True, verbose_name='sig lock'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='scale_lowerbound',
            field=models.FloatField(default=0, verbose_name='sig lower bound'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='scale_upperbound',
            field=models.FloatField(default=0, verbose_name='sig upper bound'),
        ),
    ]
