# Generated by Django 2.2.7 on 2019-12-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20191218_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='bilayer_thickness_lock',
            field=models.BooleanField(default=False, verbose_name='bilayer lock'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='bilayer_thickness_lowerbound',
            field=models.FloatField(default=0, verbose_name='bilayer lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='bilayer_thickness_upperbound',
            field=models.FloatField(default=0, verbose_name='bilayer upper bound'),
        ),
    ]
