# Generated by Django 2.2.7 on 2020-02-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20200223_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='average_vesicle_radius',
            field=models.FloatField(default=0, verbose_name='average vesicle radius'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='average_vesicle_radius_lock',
            field=models.BooleanField(default=True, verbose_name='avr lock'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='average_vesicle_radius_lowerbound',
            field=models.FloatField(default=-1, verbose_name='avr lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='average_vesicle_radius_upperbound',
            field=models.FloatField(default=1, verbose_name='avr upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='relative_size',
            field=models.FloatField(default=0, verbose_name='relative size'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='relative_size_lock',
            field=models.BooleanField(default=True, verbose_name='rs lock'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='relative_size_lowerbound',
            field=models.FloatField(default=-1, verbose_name='rs lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='relative_size_upperbound',
            field=models.FloatField(default=1, verbose_name='rs upper bound'),
        ),
    ]
