# Generated by Django 2.2.7 on 2019-12-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_auto_20191219_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_tutorial',
            field=models.BooleanField(default=True, verbose_name='display_tutorial'),
        ),
    ]
