# Generated by Django 2.2.7 on 2019-12-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_project_display_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='display_tutorial',
        ),
        migrations.AddField(
            model_name='user',
            name='display_tutorial',
            field=models.BooleanField(default=True, verbose_name='display_tutorial'),
        ),
    ]
