# Generated by Django 2.2.7 on 2020-02-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_auto_20200223_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='average_vesicle_radius',
            field=models.FloatField(default=2, verbose_name='average vesicle radius'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='average_vesicle_radius_lowerbound',
            field=models.FloatField(default=1, verbose_name='avr lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='average_vesicle_radius_upperbound',
            field=models.FloatField(default=4, verbose_name='avr upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='relative_size',
            field=models.FloatField(default=2, verbose_name='relative size'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='relative_size_lowerbound',
            field=models.FloatField(default=1, verbose_name='rs lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='relative_size_upperbound',
            field=models.FloatField(default=4, verbose_name='rs upper bound'),
        ),
    ]
