# Generated by Django 2.2.7 on 2020-02-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20200223_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='average_vesicle_radius',
            field=models.FloatField(default=500, verbose_name='average vesicle radius'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='average_vesicle_radius_lowerbound',
            field=models.FloatField(default=400, verbose_name='avr lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='average_vesicle_radius_upperbound',
            field=models.FloatField(default=600, verbose_name='avr upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='relative_size',
            field=models.FloatField(default=0.25, verbose_name='relative size'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='relative_size_lowerbound',
            field=models.FloatField(default=0, verbose_name='rs lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='relative_size_upperbound',
            field=models.FloatField(default=1, verbose_name='rs upper bound'),
        ),
    ]
