# Generated by Django 2.2.7 on 2019-12-19 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20191219_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_tutorial',
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_tutorial', models.BooleanField(default=True, verbose_name='display_tutorial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
