# Generated by Django 2.2.7 on 2019-12-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_auto_20191219_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='chain_volume_lowerbound',
            field=models.FloatField(default=-1, verbose_name='cv lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='chain_volume_upperbound',
            field=models.FloatField(default=1, verbose_name='cv upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='headgroup_thickness_lowerbound',
            field=models.FloatField(default=-1, verbose_name='ht lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='headgroup_thickness_upperbound',
            field=models.FloatField(default=1, verbose_name='ht upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='headgroup_volume_lowerbound',
            field=models.FloatField(default=-1, verbose_name='hv lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='headgroup_volume_upperbound',
            field=models.FloatField(default=1, verbose_name='hv upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='lipid_area_lowerbound',
            field=models.FloatField(default=-1, verbose_name='la lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='lipid_area_upperbound',
            field=models.FloatField(default=1, verbose_name='la upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='sigma_lowerbound',
            field=models.FloatField(default=-1, verbose_name='sig lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='sigma_upperbound',
            field=models.FloatField(default=1, verbose_name='sig upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='terminal_methyl_volume_lowerbound',
            field=models.FloatField(default=-1, verbose_name='tmv lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='terminal_methyl_volume_upperbound',
            field=models.FloatField(default=1, verbose_name='tmv upper bound'),
        ),
    ]
