# Generated by Django 2.2.7 on 2019-12-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_auto_20191223_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_lipid',
            name='scattering_length_adjustment',
        ),
        migrations.AddField(
            model_name='data_lipid',
            name='hg_scattering_length_adj',
            field=models.FloatField(default=0, verbose_name='head group length adjustment'),
        ),
        migrations.AddField(
            model_name='data_lipid',
            name='tg_scattering_length_adj',
            field=models.FloatField(default=0, verbose_name='tail group scattering length adjustment'),
        ),
    ]
