# Generated by Django 2.2.7 on 2020-02-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_auto_20200226_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asymmetrical_parameters',
            options={'verbose_name': 'asym parameter', 'verbose_name_plural': 'asym parameters'},
        ),
        migrations.AlterModelOptions(
            name='symmetrical_parameters',
            options={'verbose_name': 'sym parameter', 'verbose_name_plural': 'sym parameters'},
        ),
        migrations.AddField(
            model_name='project_lipid',
            name='lipid_location',
            field=models.CharField(choices=[('IN', 'Inner'), ('OUT', 'Outer'), ('BOTH', 'Both')], default='BOTH', max_length=4, verbose_name='model'),
            preserve_default=False,
        ),
    ]
