# Generated by Django 2.2.7 on 2019-12-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_auto_20191227_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atoms',
            fields=[
                ('atom_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('scattering_length', models.FloatField(default=0, verbose_name='scattering length')),
            ],
            options={
                'verbose_name': 'atom',
                'verbose_name_plural': 'atoms',
            },
        ),
        migrations.AlterField(
            model_name='lipid',
            name='hg_volume_equation',
            field=models.CharField(default='x', max_length=200, verbose_name='head group volume equation'),
        ),
        migrations.AlterField(
            model_name='lipid',
            name='tg_volume_equation',
            field=models.CharField(default='x', max_length=200, verbose_name='tail group volume equation'),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='scattering_length',
            field=models.FloatField(default=0, verbose_name='scattering length'),
        ),
    ]
