# Generated by Django 2.2.7 on 2020-03-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_auto_20200226_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipid',
            name='total_volume_equation',
            field=models.CharField(default='x', max_length=500, verbose_name='total volume equation'),
        ),
    ]
