# Generated by Django 2.2.7 on 2019-12-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_auto_20191230_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atoms',
            name='scattering_length',
        ),
        migrations.AddField(
            model_name='atoms',
            name='scattering_length_adj',
            field=models.FloatField(default=0, verbose_name='scattering length adjustment'),
        ),
        migrations.AddField(
            model_name='data_lipid',
            name='data_lipid_suffix',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
