# Generated by Django 2.2.7 on 2020-03-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_auto_20200318_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipid',
            name='total_volume_equation',
            field=models.CharField(default='x', max_length=800, verbose_name='total volume equation'),
        ),
    ]
