# Generated by Django 2.2.7 on 2019-12-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_auto_20191230_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atoms',
            new_name='Atom',
        ),
    ]
