# Generated by Django 2.2.7 on 2020-04-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_auto_20200318_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lipid_Augmentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('augmentation_suffix', models.CharField(blank=True, max_length=100)),
                ('hg_scattering_net_change', models.FloatField(default=0, verbose_name='head group scattering length net change')),
                ('tg_scattering_net_change', models.FloatField(default=0, verbose_name='tail group scattering length net change')),
                ('original_lipid_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_lipid_name', to='viewer.Lipid')),
            ],
            options={
                'verbose_name': 'lipid augmentation',
                'verbose_name_plural': 'lipid augmentations',
            },
        ),
        migrations.RemoveField(
            model_name='project_lipid',
            name='lipid_location',
        ),
        migrations.RemoveField(
            model_name='project_lipid',
            name='lipid_mol_fraction',
        ),
        migrations.CreateModel(
            name='Sample_Lipid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lipid_mol_fraction', models.FloatField(default=0, verbose_name='project_lipid_mol_fraction')),
                ('lipid_location', models.CharField(choices=[('IN', 'Inner'), ('OUT', 'Outer'), ('BOTH', 'Both')], max_length=4, verbose_name='model')),
                ('sample_lipid_augment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid_augment', to='viewer.Lipid_Augmentation')),
                ('sample_lipid_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid_name', to='viewer.Project_Lipid')),
                ('sample_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid', to='viewer.Sample')),
            ],
            options={
                'verbose_name': 'project lipid',
                'verbose_name_plural': 'project lipids',
            },
        ),
    ]
