# Generated by Django 2.2.7 on 2020-01-02 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_auto_20191230_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_lipid',
            name='hg_scattering_length_adj',
        ),
        migrations.RemoveField(
            model_name='data_lipid',
            name='tg_scattering_length_adj',
        ),
        migrations.CreateModel(
            name='Data_Lipid_Atom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lipid_atom_ammount', models.IntegerField(default=0, verbose_name='data_lipid_atom_ammount')),
                ('atom_location', models.CharField(choices=[('HG', 'Headgroup'), ('TG', 'Tailgroup')], max_length=3, verbose_name='atom_location')),
                ('data_lipid_atom_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_lipid_atom_name', to='viewer.Atom')),
                ('data_lipid_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_atom_lipid_name', to='viewer.Data_Lipid')),
            ],
            options={
                'verbose_name': 'data lipid',
                'verbose_name_plural': 'data lipids',
            },
        ),
    ]
