# Generated by Django 2.2.7 on 2020-04-09 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_auto_20200409_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipid_augmentation',
            name='augmentation_suffix',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sample_lipid',
            name='sample_lipid_augment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid_augment', to='viewer.Lipid_Augmentation'),
        ),
    ]
