# Generated by Django 2.2.7 on 2020-04-09 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_auto_20200409_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_lipid',
            name='sample_lipid_augment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid_augment', to='viewer.Lipid_Augmentation'),
        ),
    ]
