# Generated by Django 2.2.7 on 2020-01-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_auto_20200102_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_lipid_atom',
            options={'verbose_name': 'data lipid atom', 'verbose_name_plural': 'data lipid atoms'},
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='headgroup_thickness_lowerbound',
            field=models.FloatField(default=-7, verbose_name='ht lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='headgroup_thickness_upperbound',
            field=models.FloatField(default=7, verbose_name='ht upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='lipid_area_lowerbound',
            field=models.FloatField(default=-65, verbose_name='la lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='lipid_area_upperbound',
            field=models.FloatField(default=65, verbose_name='la upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='sigma_lowerbound',
            field=models.FloatField(default=-3, verbose_name='sig lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='sigma_upperbound',
            field=models.FloatField(default=3, verbose_name='sig upper bound'),
        ),
    ]
