# Generated by Django 2.2.7 on 2020-04-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_auto_20200409_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample_lipid',
            options={'verbose_name': 'sample lipid', 'verbose_name_plural': 'sample lipids'},
        ),
        migrations.AlterField(
            model_name='sample_lipid',
            name='lipid_mol_fraction',
            field=models.FloatField(default=0, verbose_name='sample_lipid_mol_fraction'),
        ),
    ]
