# Generated by Django 2.2.7 on 2020-01-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_auto_20200103_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_set',
            old_name='d2o_percentage',
            new_name='d2o_mol_fraction',
        ),
    ]
