# Generated by Django 2.2.7 on 2020-01-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0018_auto_20200106_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='electrons',
            field=models.FloatField(default=0, verbose_name='electrons'),
        ),
    ]
