# Generated by Django 2.2.7 on 2020-04-11 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0018_auto_20200409_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample_Lipid_Augmentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('augmentation_suffix', models.CharField(max_length=100)),
                ('hg_scattering_net_change', models.FloatField(default=0, verbose_name='head group scattering length net change')),
                ('tg_scattering_net_change', models.FloatField(default=0, verbose_name='tail group scattering length net change')),
                ('sample_lipid_agument_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid_augment_name', to='viewer.Sample_Lipid')),
                ('sample_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid_agument', to='viewer.Sample')),
            ],
            options={
                'verbose_name': 'sample lipid augmentation',
                'verbose_name_plural': 'sample lipid augmentations',
            },
        ),
    ]
