# Generated by Django 2.2.7 on 2020-01-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_molecule_electrons'),
    ]

    operations = [
        migrations.AddField(
            model_name='symmetrical_parameters',
            name='fit_report',
            field=models.TextField(blank=models.FloatField(default=1, verbose_name='tmv upper bound'), verbose_name='fitted parameter report'),
        ),
    ]
