# Generated by Django 2.2.7 on 2020-04-11 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_sample_lipid_augmentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample_lipid_augmentation',
            name='sample_title',
        ),
    ]
