# Generated by Django 2.2.7 on 2020-01-12 23:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0020_symmetrical_parameters_fit_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='fit_report',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None, verbose_name='fitted parameter report'),
        ),
    ]
