# Generated by Django 2.2.7 on 2020-04-11 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0020_remove_sample_lipid_augmentation_sample_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_lipid_augmentation',
            name='sample_title',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid_agument', to='viewer.Sample'),
            preserve_default=False,
        ),
    ]
