# Generated by Django 2.2.7 on 2020-04-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0021_sample_lipid_augmentation_sample_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipid_augmentation',
            name='tmv_scattering_net_change',
            field=models.FloatField(default=0, verbose_name='tail group scattering length net change'),
        ),
        migrations.AddField(
            model_name='sample_lipid_augmentation',
            name='tmv_scattering_net_change',
            field=models.FloatField(default=0, verbose_name='tail group scattering length net change'),
        ),
    ]
