# Generated by Django 2.2.7 on 2020-04-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0023_auto_20200413_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample_lipid_augmentation',
            name='sample_lipid_agument_name',
        ),
        migrations.RemoveField(
            model_name='sample_lipid_augmentation',
            name='sample_title',
        ),
        migrations.AddField(
            model_name='sample_lipid',
            name='sample_lipid_custom_augment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid_custom_augment', to='viewer.Sample_Lipid_Augmentation'),
        ),
    ]
