# Generated by Django 2.2.7 on 2020-04-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0024_auto_20200413_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_lipid',
            name='sample_lipid_augment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid_augment', to='viewer.Lipid_Augmentation'),
        ),
        migrations.AlterField(
            model_name='sample_lipid',
            name='sample_lipid_custom_augment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid_custom_augment', to='viewer.Sample_Lipid_Augmentation'),
        ),
    ]
