# Generated by Django 2.2.7 on 2020-01-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0025_auto_20200113_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='background_lock',
            field=models.BooleanField(default=True, verbose_name='bg lock'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='background_lowerbound',
            field=models.FloatField(default=0, verbose_name='bg lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='background_upperbound',
            field=models.FloatField(default=0, verbose_name='bg upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='scale_lock',
            field=models.BooleanField(default=True, verbose_name='scale lock'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='scale_lowerbound',
            field=models.FloatField(default=0, verbose_name='scale lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='scale_upperbound',
            field=models.FloatField(default=0, verbose_name='scale upper bound'),
        ),
    ]
