# Generated by Django 2.2.7 on 2020-04-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0025_auto_20200413_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_lipid',
            name='data_lipid_name',
        ),
        migrations.RemoveField(
            model_name='data_lipid',
            name='data_set_title',
        ),
        migrations.RemoveField(
            model_name='data_lipid_atom',
            name='data_lipid_atom_name',
        ),
        migrations.RemoveField(
            model_name='data_lipid_atom',
            name='data_lipid_name',
        ),
        migrations.DeleteModel(
            name='Atom',
        ),
        migrations.DeleteModel(
            name='Data_Lipid',
        ),
        migrations.DeleteModel(
            name='Data_Lipid_Atom',
        ),
    ]
