# Generated by Django 2.2.7 on 2020-04-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0026_auto_20200413_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='compound_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='compound name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='model_type',
            field=models.CharField(choices=[('SM', 'Symmetrical'), ('AS', 'Asymmetrical')], max_length=3, verbose_name='model type'),
        ),
    ]
