# Generated by Django 2.2.7 on 2020-01-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0026_auto_20200113_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='background_lowerbound',
            field=models.FloatField(default=-1, verbose_name='bg lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='background_upperbound',
            field=models.FloatField(default=1, verbose_name='bg upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='scale_lowerbound',
            field=models.FloatField(default=-2, verbose_name='scale lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='scale_upperbound',
            field=models.FloatField(default=2, verbose_name='scale upper bound'),
        ),
    ]
