# Generated by Django 2.2.7 on 2020-01-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0027_auto_20200113_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='background_lock',
            field=models.BooleanField(default=False, verbose_name='bg lock'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='scale_lock',
            field=models.BooleanField(default=False, verbose_name='scale lock'),
        ),
    ]
