# Generated by Django 2.2.7 on 2020-01-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0028_auto_20200113_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lipid',
            name='hg_volume_equation',
        ),
        migrations.RemoveField(
            model_name='lipid',
            name='tg_volume_equation',
        ),
        migrations.AddField(
            model_name='lipid',
            name='hg_volume',
            field=models.FloatField(default=0, verbose_name='head group volume'),
        ),
        migrations.AddField(
            model_name='lipid',
            name='total_volume_equation',
            field=models.CharField(default='x', max_length=200, verbose_name='total volume equation'),
        ),
    ]
