# Generated by Django 2.2.7 on 2020-04-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0028_auto_20200419_1904'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='data_set',
            unique_together=set(),
        ),
    ]
