# Generated by Django 2.2.7 on 2020-04-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0029_auto_20200420_1447'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='data_set',
            unique_together={('sample_title', 'data_set_title')},
        ),
    ]
