# Generated by Django 2.2.7 on 2020-04-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0030_auto_20200420_1753'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='data_set',
            unique_together=set(),
        ),
    ]
