# Generated by Django 2.2.7 on 2020-01-17 17:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0030_auto_20200114_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='background',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='background_lock',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='background_lowerbound',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='background_upperbound',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='scale_lock',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='scale_lowerbound',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='scale_upperbound',
        ),
        migrations.AddField(
            model_name='data_set',
            name='background',
            field=models.FloatField(default=0, verbose_name='background'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='background_lock',
            field=models.BooleanField(default=False, verbose_name='bg lock'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='background_lowerbound',
            field=models.FloatField(default=-1, verbose_name='bg lower bound'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='background_upperbound',
            field=models.FloatField(default=1, verbose_name='bg upper bound'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='q_ranged_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None, verbose_name='q ranged values'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='scale',
            field=models.FloatField(default=1, verbose_name='scale'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='scale_lock',
            field=models.BooleanField(default=False, verbose_name='scale lock'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='scale_lowerbound',
            field=models.FloatField(default=-2, verbose_name='scale lower bound'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='scale_upperbound',
            field=models.FloatField(default=2, verbose_name='scale upper bound'),
        ),
    ]
