# Generated by Django 2.2.7 on 2020-07-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0031_auto_20200420_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='advanced_options',
            field=models.BooleanField(default=False, verbose_name='allow advanced options'),
        ),
    ]
