# Generated by Django 2.2.7 on 2020-01-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0032_auto_20200119_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='symmetrical_parameters',
            name='water_volume',
            field=models.FloatField(default=0, verbose_name='vesicle radius'),
        ),
    ]
