# Generated by Django 2.2.13 on 2020-07-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0032_project_advanced_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='institution',
            field=models.CharField(default='None', max_length=800, verbose_name='user institution'),
        ),
    ]
