# Generated by Django 2.2.7 on 2020-01-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0033_symmetrical_parameters_water_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_set',
            name='q_max_index',
        ),
        migrations.RemoveField(
            model_name='data_set',
            name='q_min_index',
        ),
        migrations.RemoveField(
            model_name='symmetrical_parameters',
            name='water_volume',
        ),
        migrations.AddField(
            model_name='data_set',
            name='max_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='max index'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='min_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='min index'),
        ),
    ]
