# Generated by Django 2.2.13 on 2020-07-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0033_extendeduser_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='institution',
            field=models.CharField(default='None', max_length=800, verbose_name='institution'),
        ),
    ]
