# Generated by Django 2.2.13 on 2020-07-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0034_auto_20200705_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='institution',
            field=models.CharField(max_length=500, verbose_name='institution'),
        ),
    ]
