# Generated by Django 2.2.13 on 2020-07-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0035_auto_20200705_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='institution',
            field=models.CharField(default='None', max_length=500, verbose_name='institution'),
        ),
    ]
