# Generated by Django 2.2.7 on 2020-01-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0035_auto_20200120_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
