# Generated by Django 2.2.7 on 2020-01-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0036_auto_20200121_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='scale_lowerbound',
            field=models.FloatField(default=1e-06, verbose_name='scale lower bound'),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='scale_upperbound',
            field=models.FloatField(default=10, verbose_name='scale upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='headgroup_thickness',
            field=models.FloatField(default=8, verbose_name='headgroup thickness'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='headgroup_thickness_lowerbound',
            field=models.FloatField(default=5, verbose_name='ht lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='headgroup_thickness_upperbound',
            field=models.FloatField(default=15, verbose_name='ht upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='lipid_area_lowerbound',
            field=models.FloatField(default=40, verbose_name='la lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='lipid_area_upperbound',
            field=models.FloatField(default=80, verbose_name='la upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='sigma_lowerbound',
            field=models.FloatField(default=2, verbose_name='sig lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='sigma_upperbound',
            field=models.FloatField(default=4, verbose_name='sig upper bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='terminal_methyl_volume',
            field=models.FloatField(default=55, verbose_name='terminal methyl volume'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='terminal_methyl_volume_lowerbound',
            field=models.FloatField(default=45, verbose_name='tmv lower bound'),
        ),
        migrations.AlterField(
            model_name='symmetrical_parameters',
            name='terminal_methyl_volume_upperbound',
            field=models.FloatField(default=60, verbose_name='tmv upper bound'),
        ),
    ]
