# Generated by Django 2.2.13 on 2020-07-29 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0037_project_user_lipid_volume_user_lipid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_lipid',
            name='project_lipid_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_lipid_name', to='viewer.Lipid'),
        ),
    ]
