# Generated by Django 2.2.13 on 2020-07-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0038_auto_20200729_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_lipid',
            name='project_user_lipid_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_user_lipid_name', to='viewer.User_Lipid'),
        ),
        migrations.AlterField(
            model_name='project_user_lipid_volume',
            name='project_user_lipid_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_user_lipid_volume_name', to='viewer.User_Lipid'),
        ),
    ]
