# Generated by Django 2.2.13 on 2020-07-29 19:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0039_auto_20200729_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipid',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=False, populate_from='lipid_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='molecule',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=False, populate_from='compund_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_lipid',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=False, populate_from='user_lipid_name'),
            preserve_default=False,
        ),
    ]
