# Generated by Django 2.2.13 on 2020-07-29 22:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0040_auto_20200729_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipid',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='lipid_name'),
        ),
    ]
