# Generated by Django 2.2.13 on 2020-07-29 22:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0041_auto_20200729_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='compund_name'),
        ),
        migrations.AlterField(
            model_name='user_lipid',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='user_lipid_name'),
        ),
    ]
