# Generated by Django 2.2.13 on 2020-08-19 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0042_auto_20200729_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample_lipid',
            name='sample_lipid_augment',
        ),
        migrations.RemoveField(
            model_name='sample_lipid',
            name='sample_lipid_custom_augment',
        ),
        migrations.CreateModel(
            name='Data_Sample_Lipid_Augment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_lipid_augment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid_augment', to='viewer.Lipid_Augmentation')),
                ('sample_lipid_custom_augment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid_custom_augment', to='viewer.Sample_Lipid_Augmentation')),
                ('sample_lipid_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sample_lipid_name', to='viewer.Sample_Lipid')),
            ],
            options={
                'verbose_name': 'data lipid augment',
                'verbose_name_plural': 'data lipid augments',
            },
        ),
    ]
