# Generated by Django 2.2.13 on 2020-08-20 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0044_data_sample_lipid_augment_data_set_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_lipid',
            name='sample_lipid_custom_augment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_lipid_custom_augment', to='viewer.Sample_Lipid_Augmentation'),
        ),
        migrations.AlterField(
            model_name='data_sample_lipid_augment',
            name='sample_lipid_custom_augment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sample_lipid_custom_augment', to='viewer.Sample_Lipid'),
        ),
    ]
