# Generated by Django 2.2.13 on 2020-08-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0047_sample_lipid_augmentation_sample_lipid_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample_lipid_augmentation',
            old_name='tmg_scattering_net_change',
            new_name='tm_scattering_net_change',
        ),
    ]
