# Generated by Django 2.2.13 on 2020-08-20 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0048_auto_20200819_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_sample_lipid_augment',
            name='sample_lipid_custom_augment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sample_lipid_custom_augment', to='viewer.Sample_Lipid_Augmentation'),
        ),
    ]
