# Generated by Django 2.2.24 on 2021-10-28 22:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0050_auto_20201105_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='compound_name'),
        ),
    ]
